services:
  postgres:
    image: postgres:15
    container_name: neuropsych-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: neuropsych
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neuropsych_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: neuropsych-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: